PYTHON = python3
BLUE='\033[0;34m'
NC='\033[0m' # No Color
.PHONY: test format docs_help

.DEFAULT_GOAL := help
.PHONY: test help

all: help

setup:
	poetry install
	poetry run pre-commit install
	poetry shell

run:
	python -m streamlit run Brahma_Functions.py

test:
	python tests/test_ai_func.py
	python tests/test_ai_fn.py

clean:
	rm -rf __pycache__
	find . -type f -name '*.pyc' -delete

docs_build:
	cd docs && poetry run make html

format:
	poetry run black .

docs_clean:
	$(MAKE) -C docs clean

help:
	@echo "----------------------HELP--------------------------------------"
	@echo 'setup               - setup the project'
	@echo 'run                 - run the project'
	@echo 'test                - run unit tests'
	@echo 'format              - run code formatters'
	@echo 'docs_clean          - clean the documentation build artifacts'
	@echo 'docs_build          - build the documentation'
	@echo "----------------------------------------------------------------"
